# defaults:
#  - model: lstm
#  - override hydra/launcher: joblib

test_run: true
  

station_code: SF_0003
pred_hour: 1
model_name: lstm

api_version: 1

# seed: 0
# train_mode: hpo
# single_run: False

log_prefix: ./data/log/${station_code}/${pred_hour}/${model_name}
hydra:
  run:
    dir: ${log_prefix}/outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  
  sweep:
    dir: ${log_prefix}/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}    

template:
  data: ftp://{ftp_user}:{ftp_password}@{ftp_host}/public/Data/2021_data/data/{station_code}.pkl
  dataset: ftp://{ftp_user}:{ftp_password}@{ftp_host}/public/Data/2021_data/dataset/{station_code}.pkl


# wd: /workspace
# dataset_root: /dataset
dataset_path: data/processed/${station_code}.pkl
# result_dest: ${wd}/result/${model}/${station_code}_${model}_${pred_hour}
# scratch_dest: ${wd}/result/${model}/${station_code}_${model}_${pred_hour}

code_name: 
  SF_0002: 부산항신항
  SF_0003: 인천항
  SF_0004: 평택당진항
  SF_0005: 군산항
  SF_0006: 대산항
  SF_0007: 목포항
  SF_0008: 여수광양항
  SF_0009: 해운대
  SF_0011: 포항항


# env:
#   CUDA_VISIBLE_DEVICES: '2'
# ray:
#   init:
#     num_cpus: 50
#     num_gpus: 1
      
trainer_config:
  max_epochs: 50
  gpus: 1

# data_config: 
#   use_relabel: False
#   use_reweight: False

optuna_config:
  n_trials: 1
  # n_jobs: 1
  time_budget: 1000000
  study_name: ${station_code}_${pred_hour}_${model_name}
  # storage: redis://@192.168.121.231:6379/db
  storage: sqlite:///${optuna_config.study_name}
  # storage: 'sqlite:///:memory:'
  load_if_exists: false



